drop table if exists users;

create table users
(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(100) unique not null,
    phone_number varchar unique not null,
    password varchar not null,
    registered_at timestamp default now() not null
);


