drop table if exists users;

create table users
(
    id            int generated by default as identity primary key,
    name          varchar(100)            not null,
    email         varchar(100) unique     not null,
    phone_number  varchar(10) unique      not null,
    password      varchar(256)            not null,
    registered_at timestamp default now() not null
);

insert into users(name, email, phone_number, password)
values ('User', 'user@yandex.ru', '9006005040', 'password'),
       ('Admin', 'admin@mail.ru', '9007008060', 'password');

