drop table if exists users;
drop table if exists excursion;

create table users
(
    id            int generated by default as identity primary key,
    name          varchar(100)            not null,
    email         varchar(100) unique     not null,
    phone_number  varchar(10) unique      not null,
    password      varchar(256)            not null,
    registered_at timestamp default now() not null,
    role          varchar(100)            not null
);

create table excursion
(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    date date,
    description varchar(300),
    price int
);

